### ISSUE TITLE
Support for empty jobs array to enqueueBatch

### ISSUE THREAD

**Issue by dewalddp** [uafrica/delayed-jobs#14]
Currently `enqueueBatch` does not seem to support empty jobs array

## Steps to Reproduce

Call `enqueueBatch` with empty `$jobsToEnqueue`

## Actual Behavior

```
 - Execution failed :: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
#0 /var/www/uafrica.com-2.0/releases/339/html/vendor/cakephp/cakephp/src/Database/Statement/MysqlStatement.php(39): PDOStatement->execute(NULL)
#1 /var/www/uafrica.com-2.0/releases/339/html/vendor/cakephp/cakephp/src/Database/Connection.php(301): Cake\Database\Statement\MysqlStatement->execute()
#2 /var/www/uafrica.com-2.0/releases/339/html/vendor/cakephp/cakephp/src/Database/Query.php(213): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#3 /var/www/uafrica.com-2.0/releases/339/html/vendor/uafrica/delayed-jobs/src/Model/Table/DelayedJobsTable.php(149): Cake\Database\Query->execute()
#4 /var/www/uafrica.com-2.0/releases/339/html/vendor/cakephp/cakephp/src/Database/Connection.php(668): DelayedJobs\Model\Table\DelayedJobsTable->DelayedJobs\Model\Table\{closure}(Object(Cake\Database\Connection))
#5 /var/www/uafrica.com-2.0/releases/339/html/vendor/uafrica/delayed-jobs/src/Model/Table/DelayedJobsTable.php(156): Cake\Database\Connection->transactional(Object(Closure))
#6 /var/www/uafrica.com-2.0/releases/339/html/vendor/uafrica/delayed-jobs/src/Datasource/TableDatasource.php(50): DelayedJobs\Model\Table\DelayedJobsTable->persistJobs(Array)
#7 /var/www/uafrica.com-2.0/releases/339/html/vendor/uafrica/delayed-jobs/src/DelayedJob/JobManager.php(179): DelayedJobs\Datasource\TableDatasource->persistJobs(Array)
#8 /var/www/uafrica.com-2.0/releases/339/html/vendor/uafrica/delayed-jobs/src/DelayedJob/EnqueueTrait.php(66): DelayedJobs\DelayedJob\JobManager->enqueueBatch(Array)
```

## Desired Behavior

No error

**Comment by dewalddp** [comment]
Thanks!
For future reference: fixed in https://github.com/uafrica/delayed-jobs/pull/16
